### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

site_name: Documentação do Bootstrap 5.3
site_description: Documentação do Bootstrap 5.3

extra:
  blog: https://blog.getbootstrap.com
  cdn:
    css: https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css
    css_hash: sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH
    js: https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js
    js_bundle: https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
    js_bundle_hash: sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz
    js_hash: sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy
    popper: https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js
    popper_esm: https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js
    popper_hash: sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r
  current_ruby_version: 5.3.3
  current_version: 5.3.3
  docs_version: 5.3
  download:
    dist: https://github.com/twbs/bootstrap/releases/download/v5.3.3/bootstrap-5.3.3-dist.zip
    dist_examples: https://github.com/twbs/bootstrap/releases/download/v5.3.3/bootstrap-5.3.3-examples.zip
    source: https://github.com/twbs/bootstrap/archive/v5.3.3.zip
  repo: https://github.com/twbs/bootstrap
  twitter: getbootstrap

### navigation ###

nav:
  - Começando:
      - Introdução: comecando/introducao.md
      - Baixar: comecando/baixar.md
      - Conteúdo: comecando/conteudo.md
      - Navegadores e Dispositivos: comecando/navegadores-dispositivos.md
      - JavaScript: comecando/javascript.md
      - Webpack: getting-started/webpack.md
      - Parcel: getting-started/parcel.md
      - Vite: getting-started/vite.md
      - Accessibility: getting-started/accessibility.md
      - RFS: getting-started/rfs.md
      - RTL: getting-started/rtl.md
      - Contribute: getting-started/contribute.md
  - Customize:
      - Overview: customize/overview.md
      - Sass: customize/sass.md
      - Options: customize/options.md
      - Color: customize/color.md
      - Color modes: customize/color-modes.md
      - Components: customize/components.md
      - CSS variables: customize/css-variables.md
      - Optimize: customize/optimize.md
  - Layout:
      - Breakpoints: layout/breakpoints.md
      - Containers: layout/containers.md
      - Grid: layout/grid.md
      - Columns: layout/columns.md
      - Gutters: layout/gutters.md
      - Utilities: layout/utilities.md
      - Z-index: layout/z-index.md
      - CSS Grid: layout/css-grid.md
  - Content:
      - Reboot: content/reboot.md
      - Typography: content/typography.md
      - Images: content/images.md
      - Tables: content/tables.md
      - Figures: content/figures.md
  - Forms:
      - Overview: forms/overview.md
      - Form control: forms/form-control.md
      - Select: forms/select.md
      - Checks & radios: forms/checks-radios.md
      - Range: forms/range.md
      - Input group: forms/input-group.md
      - Floating labels: forms/floating-labels.md
      - Layout: forms/layout.md
      - Validation: forms/validation.md
  - Components:
      - Accordion: components/accordion.md
      - Alerts: components/alerts.md
      - Badge: components/badge.md
      - Breadcrumb: components/breadcrumb.md
      - Buttons: components/buttons.md
      - Button group: components/button-group.md
      - Card: components/card.md
      - Carousel: components/carousel.md
      - Close button: components/close-button.md
      - Collapse: components/collapse.md
      - Dropdowns: components/dropdowns.md
      - List group: components/list-group.md
      - Modal: components/modal.md
      - Navbar: components/navbar.md
      - Navs & tabs: components/navs-tabs.md
      - Offcanvas: components/offcanvas.md
      - Pagination: components/pagination.md
      - Placeholders: components/placeholders.md
      - Popovers: components/popovers.md
      - Progress: components/progress.md
      - Scrollspy: components/scrollspy.md
      - Spinners: components/spinners.md
      - Toasts: components/toasts.md
      - Tooltips: components/tooltips.md
  - Helpers:
      - Clearfix: helpers/clearfix.md
      - Color & background: helpers/color-background.md
      - Colored links: helpers/colored-links.md
      - Focus ring: helpers/focus-ring.md
      - Icon link: helpers/icon-link.md
      - Position: helpers/position.md
      - Ratio: helpers/ratio.md
      - Stacks: helpers/stacks.md
      - Stretched link: helpers/stretched-link.md
      - Text truncation: helpers/text-truncation.md
      - Vertical rule: helpers/vertical-rule.md
      - Visually hidden: helpers/visually-hidden.md
  - Utilities:
      - API: utilities/api.md
      - Background: utilities/background.md
      - Borders: utilities/borders.md
      - Colors: utilities/colors.md
      - Display: utilities/display.md
      - Flex: utilities/flex.md
      - Float: utilities/float.md
      - Interactions: utilities/interactions.md
      - Link: utilities/link.md
      - Object fit: utilities/object-fit.md
      - Opacity: utilities/opacity.md
      - Overflow: utilities/overflow.md
      - Position: utilities/position.md
      - Shadows: utilities/shadows.md
      - Sizing: utilities/sizing.md
      - Spacing: utilities/spacing.md
      - Text: utilities/text.md
      - Vertical align: utilities/vertical-align.md
      - Visibility: utilities/visibility.md
      - Z-index: utilities/z-index.md
  - Extend:
      - Approach: extend/approach.md
      - Icons: extend/icons.md
  - About:
      - Overview: about/overview.md
      - Team: about/team.md
      - Brand: about/brand.md
      - License: about/license.md
      - Translations: about/translations.md
  - Migration: migration.md
